### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vimaxus** [lvonasek/tango#12]
Thank you so much for this most useful tango app. (to me at least)

How do I resume scanning after the overbright message?
I get an offset 3d view and whatever I do it doesn't resume scanning
Well sometimes, rarely, it resumes but when I get to the ceiling or whatever white area I get the message and get stuck again.

If I choose resume scanning from the menu I have to align a weird white photo (last photo?) that is unusable because it's some area of the ceiling without any references. Can we at least choose what photo we want to find again in order to resume from a known location?

**Comment by vimaxus** [comment]
How do I resume scanning after the overbright message?
I get an offset 3d view and whatever I do it doesn't resume scanning
Well sometimes, rarely, it resumes but when I get to the ceiling or whatever white area I get the message and get stuck again.

If I choose resume scanning from the menu I have to align a weird white photo (last photo?) that is unusable because it's some area of the ceiling without any references. Can we at least choose what photo we want to find again in order to resume from a known location?

**Comment by lvonasek** [comment]
Hi,

motion tracking is based on comparing photos using fisheye camera (with field of view about 150 degress). When fisheye camera gets blinded the motion tracking stops working. Resuming of it is complicated and app developers cannot affect it (due to missing API). Tango resumes it automatically when you point on geometrically rich objects (many edges, contrast colors). But it is not working so well (as whole Tango technology).

When you go into menu then you lose complete information about the area so Tango does not recognize it anymore - thats why there is matching with last frame. Tango API does not allow to save area information when I use "drifting correction". (Without it ita useless)

With current Tango technology it is not possible to do it better. You can contact Tango SDK developers but they answer almost never.

I will at least add possibility to select photo for matching.

**Comment by vimaxus** [comment]
Ok I understand. Thanks for answering so quickly.

Maybe an option not to stop scanning when it's too bright? (what exactly happens or triggers the fixed thirdperson view?)

The official Constructor Developer Tool frequently gives a similar message but the scanning carries on.
I do however prefer your implementation. It is a lot better as the scanning resolution is adjustable, the export works correctly and it feels a lot more fluent.

**Comment by lvonasek** [comment]
Thats impossible, when it is too bright Tango stops updating pose (device position and rotation) so I have no clue where to place new geometry.
