### ISSUE TITLE
Flickering textures in some models

### ISSUE THREAD

**Issue by helipiotr** [lvonasek/tango#14]
Hi there,
I took a simple scan of a flat in .obj file format using Open Constructor. While viewing in obj VR viewer, some textures are flickering and it is impossible to use the app comfortably. I attach the files to see whether this error is reproducible:

https://drive.google.com/open?id=0BwgFgo0KPUHpdC1vWWpsVzM2MVk

Please let me know whether you have any idea as to how debug this issue and whether it persists on your setup. The error occured with Zenfone AR , compilation number:
NRD90M.WW_Phone-14.1600.1708.30-20170818

Thanks in advance!

**Comment by lvonasek** [comment]
Hi,

I reproduced it without problems. The issue is connected with too much geometry for VR rendering. I modified amount of geometry that can be passed per one texture which makes rendering faster and issue in this model disappears. Please sign into beta of the app (open app on Google Play and go on the bottom of the page). In beta version 0.3.1 is the issue fixed for your setup.

Have a nice weekend.

**Comment by helipiotr** [comment]
Hi, the issue also worked on my setup. Thanks for help!

**Comment by lvonasek** [comment]
Ok, I published the version for all users
