### ISSUE TITLE
[Question] Do I need some special libraries or configurations to compile/extend this project?

### ISSUE THREAD

**Issue by ysinotelodigo** [lvonasek/tango#16]
Hello,

First of all, I would like to tell you that I like your project. It is simple to use and it has a great potential.
I would like to extend the functionalities of this application for a reseach project. However, I got some errors before compiling for first time (without any modification).

Error while executing process C:\Users\<user>\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\<user>\Desktop\tango-master\open_constructor\app\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\<user>\Desktop\tango-master\open_constructor\app\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-23 NDK_OUT=C:/Users/<user>/Desktop/tango-master/open_constructor/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\<user>\Desktop\tango-master\open_constructor\app\build\intermediates\ndkBuild\debug\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
process_begin: CreateProcess(NULL, "", ...) failed.

*The user has been changed by <user>

I create the NDK_PROJECT_PATH operation system variable pointing to  C:\Users\<user>\Desktop\tango-master\open_constructor, but it seems not to work.

I would like to include Area-Learning feature while the application is modeling an environment. I guess that this features will not be difficult to add.

You can recommend an Android NDK guide if you think it is necesary. I do not want to stole your time.

**Comment by lvonasek** [comment]
Hi,

you don't need any additional libraries. But it compiles on Linux only. I do not know why it does not work on Windows.

About area-learning, there was version supporting it (0.7.3, I am not sure if it was already compatible with Zenfone, probably not). The problem is that Tango does not support area learning and drifting correction together (you can have one or second but not both). So I put it away.

If you need to export ADF only, thats somehow possible but reload it with my config not.
