### ISSUE TITLE
EXPORT .OBJ TO PC

### ISSUE THREAD

**Issue by GiorgosTzagk** [lvonasek/tango#21]
I used to be able to export the .obj file to my pc and now i cant find it. Can you please help?

**Comment by lvonasek** [comment]
The files are stored in internal storage/Models/model_name. Whats new in the last versions is that the model and all textures are stored together in one folder (so one folder is one scan).

Note that on PC you do not have to see complete content of you device (because of issues in MTP protocol). Take a look into folder in mobile file browser.

I am closing this issue but feel free to ask more questions here.
