### ISSUE TITLE
Bugfix for 'multiple targets' NDK compilation error

### ISSUE THREAD

**Issue by greymfm** [lvonasek/tango#22]
Hello,
The code will not compile until the file at 'third_party/libfreetype/Android.mk' has been corrected:

the first line should be:
LOCAL_PATH:= $(call my-dir)

and not an absolute path :-)

PS: Excellent code you wrote to study NDK and Tango for me :-)  (have only extensively used Tango via Java and never used the NDK yet...)

Regards,
Alexander

**Comment by greymfm** [comment]
Yeah, if you remove it, it will compile too on Windows - however the absolute path option is wrong (believe me). I'm looking for an outdoor SLAM solution in bright sunlight and changing light conditions. tried this with the phone with limited success so far...

**Comment by lvonasek** [comment]
Hm, compiling on Windows does not work for me. Anyway it is working for you also I close this bug.

About outdoor SLAM - there is used drifting correction which makes motion tracking more unaccurate but it makes 3D reconstruction more continuous. The problem with Tango's SLAM is that they are using just fisheye camera and nothing else. Optimal would be to use RGBD SLAM but yoz cannot lock the color camera capture settings. And on Asus Zenfone AR you cannot read the fisheye camera data (due to changes in Tango on Android7). There would be possible to read fisheye camera data, color data and depth data, combine fisheye data with color data (to do a color calibration) and then provide data for RGBD SLAM and use it for motion tracking but that is too much work and it would work just on Lenovo Phab2Pro
