### ISSUE TITLE
Would this work on moto g5s plus?

### ISSUE THREAD

**Issue by abpavani** [lvonasek/tango#24]
I would like to try this out on moto g5s plus. Can you please provide me with the apk if it does work. Google play store link doesn't work for me

**Comment by lvonasek** [comment]
Hi,

it does not work because of this issue:
https://github.com/google-ar/arcore-android-sdk/issues/381

Here is the latest ARcore:
https://github.com/lvonasek/tango-binary/blob/master/ARcore/2018-05/ARCore_1_2.apk?raw=true

Here is the app:
https://github.com/lvonasek/tango-binary/blob/master/3DScannerForARcore/180601.apk?raw=true

I am closing this issue because it is not problem with my app but with ARcore device support.
