### ISSUE TITLE
Google Play believes this is incompatible with Zenfone AR

### ISSUE THREAD

**Issue by lonetech** [lvonasek/tango#9]
Tried to install from https://play.google.com/store/apps/details?id=com.lvonasek.openconstructor but it simply won't let me. Could you support Zenfone AR?

**Comment by lvonasek** [comment]
Hi, it is crashing on every start on Asus Zenfone AR. I am communicating with Asus about it for three weeks BUT they are really slow (or they dont answer at all sometimes). Currently without having device for debugging I cannot fix it.

**Comment by lonetech** [comment]
I just got one, so perhaps I might help with debugging? Will take me a while to get the development environment etc set up.

**Comment by lvonasek** [comment]
Would be great. Install Android Studio, clone my git repository of release 0.6.5 and build it. Then we can continue on Team Viewer or something like that.

**Comment by lonetech** [comment]
Well, so far I'm stuck at "build it". Android Studio doesn't include the VR or Tango SDKs afaict, and the getting started documents don't explain how to add them; it looks like the gradle files do refer to the repo etc, but I don't know what Maven is and Android Studio hides the build.gradle. I'll probably get somewhere eventually.

**Comment by lvonasek** [comment]
SDK is a part of git repository. You should import open_constructor only. Not whole repository.

**Comment by lonetech** [comment]
Stuck at an utterly uninformative error where ndk-bundle says it has multiple target patterns on an empty line in build-binary.mk. Tiring of these helpful GUI things that break in funny ways.

**Comment by lvonasek** [comment]
Please send a screenshot of your android studio

**Comment by lonetech** [comment]
https://drive.google.com/file/d/0B4QX7tC7UWZdSUgwQXl5NG9HWXc/view?usp=sharing

**Comment by lvonasek** [comment]
Ok, clone current repository instead of 0.6.5 and try if it starts working.

**Comment by lonetech** [comment]
It looks like master gives me the silent restart, v0.6.5 gets me a popup admitting the app stopped. The debugger merely says process finished with exit code 9.

**Comment by lvonasek** [comment]
Ok, I will add path of TangoCore during next week. Now I am on vacation (without PC)

**Comment by lonetech** [comment]
This is a bit tricky. Google's samples aren't working right either. I don't know how you're expected to load the C API.

**Comment by lvonasek** [comment]
I will load it in try-catch, if it fails then I load other path... It is no problem

**Comment by lvonasek** [comment]
Can you try if tango java examples work on Zenfone?

**Comment by cefoot** [comment]
just leaving comment to show my interest
my zenfone ar should arrive next week. than i could possibly help ;)

**Comment by lvonasek** [comment]
try pls current master if it works on Zenfone

**Comment by rayhero** [comment]
I fork current master branch and found it still not work on zenfone AR
below is the crash log:

07-12 15:35:21.555 8233-8318/com.lvonasek.openconstructor E/linker: library "/system/app/TangoCore/lib/arm64/libtango_client_api.so" ("/system/app/TangoCore/lib/arm64/libtango_client_api.so") needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.lvonasek.openconstructor-1/lib/arm64:/data/app/com.lvonasek.openconstructor-1/base.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstruc
07-12 15:35:21.562 8233-8318/com.lvonasek.openconstructor E/linker: library "/system/app/TangoCore/lib/arm64/libtango_client_api.so" ("/system/app/TangoCore/lib/arm64/libtango_client_api.so") needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.lvonasek.openconstructor-1/lib/arm64:/data/app/com.lvonasek.openconstructor-1/base.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstruc
07-12 15:35:21.572 8233-8318/com.lvonasek.openconstructor E/art: No implementation found for void com.lvonasek.openconstructor.main.JNI.onTangoServiceConnected(android.os.IBinder, double, double, double, int, boolean, java.lang.String) (tried Java_com_lvonasek_openconstructor_main_JNI_onTangoServiceConnected and Java_com_lvonasek_openconstructor_main_JNI_onTangoServiceConnected__Landroid_os_IBinder_2DDDIZLjava_lang_String_2)
07-12 15:35:21.573 8233-8318/com.lvonasek.openconstructor E/AndroidRuntime: FATAL EXCEPTION: Thread-6
                                                                            Process: com.lvonasek.openconstructor, PID: 8233
                                                                            java.lang.UnsatisfiedLinkError: No implementation found for void com.lvonasek.openconstructor.main.JNI.onTangoServiceConnected(android.os.IBinder, double, double, double, int, boolean, java.lang.String) (tried Java_com_lvonasek_openconstructor_main_JNI_onTangoServiceConnected and Java_com_lvonasek_openconstructor_main_JNI_onTangoServiceConnected__Landroid_os_IBinder_2DDDIZLjava_lang_String_2)
                                                                                at com.lvonasek.openconstructor.main.JNI.onTangoServiceConnected(Native Method)
                                                                                at com.lvonasek.openconstructor.main.OpenConstructor$1$1.run(OpenConstructor.java:138)
                                                                                at java.lang.Thread.run(Thread.java:761)
07-12 15:35:21.583 8233-8316/com.lvonasek.openconstructor E/art: No implementation found for void com.lvonasek.openconstructor.main.JNI.onGlSurfaceChanged(int, int) (tried Java_com_lvonasek_openconstructor_main_JNI_onGlSurfaceChanged and Java_com_lvonasek_openconstructor_main_JNI_onGlSurfaceChanged__II)

**Comment by rayhero** [comment]
I also try the tango java examples and it's works on Zenfone AR. How can I help you to trace the problem??

**Comment by rayhero** [comment]
The tango-examples-c is also works on Zenfone AR. For your reference

**Comment by lvonasek** [comment]
I put into master the same way of library loading like it is in examples, can you try it?

**Comment by rayhero** [comment]
ok let me try it

**Comment by rayhero** [comment]
Still have proble： the error is show below:

07-12 16:42:02.116 23091-23198/com.lvonasek.openconstructor E/JNI: ERROR! Unable to load libtango_client_api.so!
07-12 16:42:02.119 23091-23198/com.lvonasek.openconstructor E/AndroidRuntime: FATAL EXCEPTION: Thread-6
                                                                              Process: com.lvonasek.openconstructor, PID: 23091
                                                                              java.lang.UnsatisfiedLinkError: dlopen failed: library "libtango_client_api.so" not found
                                                                                  at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                                                                                  at java.lang.System.loadLibrary(System.java:1530)
                                                                                  at com.lvonasek.openconstructor.main.JNI.<clinit>(JNI.java:14)
                                                                                  at com.lvonasek.openconstructor.main.JNI.onTangoServiceConnected(Native Method)
                                                                                  at com.lvonasek.openconstructor.main.OpenConstructor$1$1.run(OpenConstructor.java:138)
                                                                                  at java.lang.Thread.run(Thread.java:761)

----------------------------------------------------------------
I also try to migrate tango-examples-c's way to load library. But it's fail on your project orz.

**Comment by rayhero** [comment]
Below is the log from tango-examples-c-master:

07-12 17:09:09.927 24453-24453/com.projecttango.examples.cpp.meshbuilder I/TangoInitializationHelper: basePath: /data/data/com.google.tango/libfiles/
07-12 17:09:09.930 24453-24453/com.projecttango.examples.cpp.meshbuilder W/linker: library "libbinder.so" ("/system/lib64/libbinder.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-12 17:09:09.931 24453-24453/com.projecttango.examples.cpp.meshbuilder W/linker: library "libcutils.so" ("/system/lib64/libcutils.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-12 17:09:09.931 24453-24453/com.projecttango.examples.cpp.meshbuilder W/linker: library "libutils.so" ("/system/lib64/libutils.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-12 17:09:09.931 24453-24453/com.projecttango.examples.cpp.meshbuilder W/linker: library "libgui.so" ("/system/lib64/libgui.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-12 17:09:09.932 24453-24453/com.projecttango.examples.cpp.meshbuilder W/linker: library "libandroid_runtime.so" ("/system/lib64/libandroid_runtime.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-12 17:09:09.932 24453-24453/com.projecttango.examples.cpp.meshbuilder W/linker: library "libui.so" ("/system/lib64/libui.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-12 17:09:10.050 24453-24453/com.projecttango.examples.cpp.meshbuilder E/linker: library "libavenhancements.so" ("/system/vendor/lib64/libavenhancements.so") needed or dlopened by "/system/lib64/libmedia.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.projecttango.examples.cpp.meshbuilder-1/lib/arm64:/system/fake-libs64:/data/app/com.projecttango.examples.cpp.meshbuilder-1/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.projecttango.examples.cpp.meshbuilder"]
07-12 17:09:10.052 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoConfig
07-12 17:09:10.052 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoPoseData
07-12 17:09:10.053 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoPointCloudData
07-12 17:09:10.053 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoEvent
07-12 17:09:10.053 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoTransformation
07-12 17:09:10.054 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoFoiResult
07-12 17:09:10.054 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoCameraIntrinsics
07-12 17:09:10.054 24453-24453/com.projecttango.examples.cpp.meshbuilder I/TangoInitializationHelper: Success! Using default/libtango_client_api.
07-12 17:09:10.055 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoAreaDescriptionMetaData
07-12 17:09:10.072 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoConfig
07-12 17:09:10.072 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoPoseData
07-12 17:09:10.072 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoPointCloudData
07-12 17:09:10.072 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoEvent
07-12 17:09:10.073 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoTransformation
07-12 17:09:10.073 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoFoiResult
07-12 17:09:10.073 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoCameraIntrinsics
07-12 17:09:10.074 24453-24485/com.projecttango.examples.cpp.meshbuilder E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoAreaDescriptionMetaData
07-12 17:09:10.076 24453-24453/com.projecttango.examples.cpp.meshbuilder V/Monotype: SetAppTypeFace- try to flip, app = com.projecttango.examples.cpp.meshbuilder

-----------------------------------------------------------
you can found the same code in tamgo-examples-c has success message:
I/TangoInitializationHelper: Success! Using default/libtango_client_api.

But in your project it will show error. Do you have some hint to let me help you find the root cause??

**Comment by rayhero** [comment]
I also found your compileSdkVersion & buildToolsVersion is not equal to tangle-examples-c. But I got compile error when I downgrade your compileSdkVersion & buildToolsVersion ...

**Comment by lvonasek** [comment]
Weird is that in examples it loads default/libtango_client_api (which I understand as some kind of fallback). 

Anyway I put it as default and maybe it will fix it. Try pls

**Comment by rayhero** [comment]
ok.let me try

**Comment by rayhero** [comment]
It's same error...orz...
log is show below:
-------------------------------------------------
07-12 17:58:27.614 6562-6680/com.lvonasek.openconstructor E/JNI: ERROR! Unable to load libtango_client_api.so!
07-12 17:58:27.617 6562-6680/com.lvonasek.openconstructor E/AndroidRuntime: FATAL EXCEPTION: Thread-6
                                                                            Process: com.lvonasek.openconstructor, PID: 6562
                                                                            java.lang.UnsatisfiedLinkError: dlopen failed: library "libtango_client_api.so" not found
                                                                                at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                                                                                at java.lang.System.loadLibrary(System.java:1530)
                                                                                at com.lvonasek.openconstructor.main.JNI.<clinit>(JNI.java:14)
                                                                                at com.lvonasek.openconstructor.main.JNI.onTangoServiceConnected(Native Method)
                                                                                at com.lvonasek.openconstructor.main.OpenConstructor$1$1.run(OpenConstructor.java:138)
                                                                                at java.lang.Thread.run(Thread.java:761)

**Comment by lvonasek** [comment]
What was the basepath? (it should be in log too)

**Comment by rayhero** [comment]
the basepath is show below:
07-12 18:21:51.775 7613-7693/com.lvonasek.openconstructor I/TangoInitHelper: basePath: /data/data/com.google.tango/libfiles/

**Comment by lvonasek** [comment]
I was googling and it seems it is connected to this:
https://developer.android.com/about/versions/nougat/android-7.0-changes.html#ndk

I downgraded target sdk which should solve the problem

**Comment by lvonasek** [comment]
Can anyone confirm that the problem is solved with last git commit?

**Comment by rayhero** [comment]
use latest update can success load library. But the app still can not enter capture mode...below is the crash log:

07-13 09:10:12.324 10444-11026/? I/TangoInitHelper: basePath: /data/data/com.google.tango/libfiles/
07-13 09:10:12.326 10444-11026/? W/linker: library "libbinder.so" ("/system/lib64/libbinder.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-13 09:10:12.326 10444-11026/? W/linker: library "libcutils.so" ("/system/lib64/libcutils.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-13 09:10:12.326 10444-11026/? W/linker: library "libutils.so" ("/system/lib64/libutils.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-13 09:10:12.326 10444-11026/? W/linker: library "libgui.so" ("/system/lib64/libgui.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-13 09:10:12.327 10444-11026/? W/linker: library "libandroid_runtime.so" ("/system/lib64/libandroid_runtime.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-13 09:10:12.327 10444-11026/? W/linker: library "libui.so" ("/system/lib64/libui.so") needed or dlopened by "/data/data/com.google.tango/libfiles/default/libtango_client_api.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
07-13 09:10:12.482 10444-11026/? E/linker: library "libavenhancements.so" ("/system/vendor/lib64/libavenhancements.so") needed or dlopened by "/system/lib64/libmedia.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.lvonasek.openconstructor-1/lib/arm64:/system/fake-libs64:/data/app/com.lvonasek.openconstructor-1/base.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a:/data/app/com.lvonasek.openconstructor-1/split_lib_slice_6_apk.apk!/l
07-13 09:10:12.484 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoConfig
07-13 09:10:12.484 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoPoseData
07-13 09:10:12.485 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoPointCloudData
07-13 09:10:12.485 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoEvent
07-13 09:10:12.485 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoTransformation
07-13 09:10:12.486 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoFoiResult
07-13 09:10:12.486 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoCameraIntrinsics
07-13 09:10:12.486 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoAreaDescriptionMetaData
07-13 09:10:12.486 10444-11026/? I/TangoInitHelper: Success! Using default/libtango_client_api.
07-13 09:10:12.503 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoConfig
07-13 09:10:12.504 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoPoseData
07-13 09:10:12.504 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoPointCloudData
07-13 09:10:12.504 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoEvent
07-13 09:10:12.505 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoTransformation
07-13 09:10:12.505 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoFoiResult
07-13 09:10:12.505 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoCameraIntrinsics
07-13 09:10:12.506 10444-11027/? E/tango: class_util.cc:20 Failed to load Java class com/google/atap/tangoservice/TangoAreaDescriptionMetaData
07-13 09:10:12.506 10444-11026/? I/tango_client_api: TangoErrorType TangoService_setBinder(void*, void*): Passing back the binder on the client end...
07-13 09:10:12.506 10444-11026/? I/ndk_camera: Starting native camera system initialization.
07-13 09:10:12.512 10444-11026/? D/ndk_camera: Camera 0 has 90 metadata tags
07-13 09:10:12.512 10444-11026/? E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
07-13 09:10:12.512 10444-11026/? W/ndk_camera: Failed to get metadata tag 1310721 for camera 0 with error code -10004
07-13 09:10:12.512 10444-11026/? E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
07-13 09:10:12.512 10444-11026/? W/ndk_camera: Failed to get metadata tag 1638401 for camera 0 with error code -10004
07-13 09:10:12.512 10444-11026/? D/ndk_camera: Camera 1 has 90 metadata tags
07-13 09:10:12.513 10444-11026/? E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
07-13 09:10:12.513 10444-11026/? W/ndk_camera: Failed to get metadata tag 1310721 for camera 1 with error code -10004
07-13 09:10:12.513 10444-11026/? E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
07-13 09:10:12.513 10444-11026/? W/ndk_camera: Failed to get metadata tag 1638401 for camera 1 with error code -10004
07-13 09:10:12.513 10444-11026/? I/ndk_camera: Camera system initialized successfully with 2 cameras.
07-13 09:10:12.513 10444-11026/? E/tango_camera_native: 2 is not a valid camera index.
07-13 09:10:12.513 10444-11026/? E/tango_camera_native: 3 is not a valid camera index.
07-13 09:10:12.513 10444-11026/? I/tango_client_api: void* TangoService_getConfig(TangoConfigType): Getting config...
07-13 09:10:12.513 7999-8978/? I/tango: java_service_entrypoint.cc:324 bool getConfig(JNIEnv*, TangoConfigType, tango_common::Config*): Getting config...
07-13 09:10:12.514 7999-8978/? I/tango: java_service_entrypoint.cc:340 bool getConfig(JNIEnv*, TangoConfigType, tango_common::Config*): Done getting config.
07-13 09:10:12.514 10444-11029/? E/tango: support_frame_helper.cc:794 TangoErrorType TangoSupport_getDoubleMatrixTransformAtTime(double, TangoCoordinateFrameType, TangoCoordinateFrameType, TangoSupport_EngineType, TangoSupport_EngineType, TangoSupport_Rotation, TangoSupport_DoubleMatrixTransformData*): pose function not initialized. Calling TangoSupport_initialize is required.
07-13 09:10:12.515 10444-11026/? I/tango_client_api: void* TangoService_getConfig(TangoConfigType): Done getting config.
07-13 09:10:12.517 10444-11026/? I/tango_client_api: TangoErrorType TangoService_connectOnPointCloudAvailable(void (*)(void*, const TangoPointCloud*), ...): Connecting callbacks...
07-13 09:10:12.517 10444-11026/? I/tango_client_api: TangoErrorType TangoService_connectOnPointCloudAvailable(void (*)(void*, const TangoPointCloud*), ...): Done connecting callbacks.
07-13 09:10:12.517 10444-11026/? I/tango_client_api: TangoErrorType TangoService_connectOnFrameAvailable(TangoCameraId, void*, void (*)(void*, TangoCameraId, const TangoImageBuffer*)): Connecting callbacks...
07-13 09:10:12.518 10444-11026/? E/NdkImageReader: AImageReader_getWindow
07-13 09:10:12.518 10444-11026/? I/tango_client_api: TangoErrorType TangoService_connectOnFrameAvailable(TangoCameraId, void*, void (*)(void*, TangoCameraId, const TangoImageBuffer*)): Done connecting callbacks.
07-13 09:10:12.518 10444-11026/? I/tango_client_api: TangoErrorType TangoService_connectOnFrameAvailable(TangoCameraId, void*, void (*)(void*, TangoCameraId, const TangoImageBuffer*)): Connecting callbacks...
07-13 09:10:12.518 10444-11026/? E/tango_client_api: Cannot register onFrameAvailable callback when onImageAvailable already registered!
07-13 09:10:12.527 10444-11026/? I/tango_camera_native: Camera 3 entering reset...
07-13 09:10:12.527 10444-11026/? I/tango_camera_native: Camera 2 entering reset...
07-13 09:10:12.527 10444-11026/? I/tango_camera_native: Camera 1 entering reset...
07-13 09:10:12.527 10444-11026/? I/tango_camera_native: Camera 1 closed.
07-13 09:10:12.527 10444-11026/? I/tango_camera_native: Camera 1 out of reset.
07-13 09:10:12.527 10444-11026/? I/tango_camera_native: Camera 0 entering reset...
07-13 09:10:12.527 10444-11026/? I/tango_camera_native: Camera 0 closed.
07-13 09:10:12.527 10444-11026/? I/tango_camera_native: Camera 0 out of reset.
07-13 09:10:12.549 3270-11020/? D/DownloadManager: [2332] Finished with status SUCCESS
07-13 09:10:12.557 1372-1504/? I/ActivityManager: Displayed com.lvonasek.openconstructor/.main.OpenConstructor: +416ms [aosp]
07-13 09:10:12.572 1372-2586/? D/GraphicsStats: Buffer count: 4
07-13 09:10:12.573 1372-2065/? I/ActivityManager: Process com.lvonasek.openconstructor (pid 10444) has died
07-13 09:10:12.573 1372-2065/? D/ActivityManager: cleanUpApplicationRecord -- 10444
07-13 09:10:12.573 1372-2065/? W/ActivityManager: App Op not allow to restart app com.lvonasek.openconstructor/10131
07-13 09:10:12.576 1372-2065/? W/ActivityManager: Force removing ActivityRecord{e970615 u0 com.lvonasek.openconstructor/.main.OpenConstructor t127}: app died, no saved state

**Comment by rayhero** [comment]
add the Device monitor screenshot:
@lvonasek 's project:
![2017-07-13 10 17 47](https://user-images.githubusercontent.com/3665120/28147945-6836bedc-67b6-11e7-9e98-3ee348ab4b10.png)

tago-examples-c's log:
![2017-07-13 10 29 50](https://user-images.githubusercontent.com/3665120/28147960-7c4da6c4-67b6-11e7-9e18-78cdaaf978fc.png)

the major different is that after connectOnFrameAvailable, the tago-examples-c show the "Connecting to Tango..." and the show the tango_service_library message. But @lvonasek 's project call TangoService_connectOnFrameAvailable twice and cause the "Cannot register onFrameAvailable error..." then stuck the process. Where @lvonasek call the connectOnFrameAvailable??

**Comment by rayhero** [comment]
finally found the root cause is @lvonasek call

**Comment by lvonasek** [comment]
OK, so it is not possible to read fisheye and color camera in the same time. That sucks. It was the key to make one of the next big feature working.

Anyway, I will wait for the next Tango SDK (which is commning hopefully 21.7.) and finish the 0.7.x version. Then I will release it on Google Play.

@rayhero thank you for your support, good job

**Comment by lvonasek** [comment]
Hi guys, here is the release candidate version: https://github.com/lvonasek/tango-binary/raw/master/OpenConstructor/077.apk can you test it if it works well on Zenfone? I am going to release it next week on Google Play.

**Comment by lonetech** [comment]
It runs on my Zenfone AR, which is a considerable improvement. In my quick test it produced some alignment issues and refused to scan some smooth plastic bits, but that seems about the state of things.

**Comment by lvonasek** [comment]
OK, thank you. It is expectable due to limitations of Tango
